import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist", "dev-dist", "src/routeTree.gen.ts"] },
  {
    files: ["**/*.{ts,tsx}"],
    extends: [js.configs.recommended, ...tseslint.configs.strictTypeChecked],
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      // useEffect is an escape hatch only — see apps/web/CLAUDE.md rule 1.
      "react-hooks/exhaustive-deps": "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/explicit-module-boundary-types": "error",
      "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
    },
  },
  {
    // Vendored shadcn primitives: regenerated by the CLI, so they are kept as
    // upstream ships them. Semantic variants added here are still reviewed.
    files: ["src/components/ui/**"],
    rules: {
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "react-refresh/only-export-components": "off",
    },
  },
  {
    // File-based routes must export both `Route` and their component by design,
    // and TanStack Router's guard API works by throwing a redirect object.
    files: ["src/routes/**/*.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
      "@typescript-eslint/only-throw-error": "off",
    },
  },
  {
    files: ["vite.config.ts", "pwa-manifest.ts", "eslint.config.js"],
    languageOptions: { globals: globals.node },
  },
);
