/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BloqueadosRouteImport } from './routes/bloqueados'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as CrearCuentaRouteImport } from './routes/crear-cuenta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as GuardadasRouteImport } from './routes/guardadas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as CocinerosCookIdRouteImport } from './routes/cocineros.$cookId'
import { Route as RecetasIndexRouteImport } from './routes/recetas.index'
import { Route as RecetasRecipeIdRouteImport } from './routes/recetas.$recipeId'
import { Route as RecetasNuevaRouteImport } from './routes/recetas.nueva'
import { Route as RecetasRecipeIdEditarRouteImport } from './routes/recetas.$recipeId_.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueadosRoute = BloqueadosRouteImport.update({
  id: '/bloqueados',
  path: '/bloqueados',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearCuentaRoute = CrearCuentaRouteImport.update({
  id: '/crear-cuenta',
  path: '/crear-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardadasRoute = GuardadasRouteImport.update({
  id: '/guardadas',
  path: '/guardadas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const CocinerosCookIdRoute = CocinerosCookIdRouteImport.update({
  id: '/cocineros/$cookId',
  path: '/cocineros/$cookId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasIndexRoute = RecetasIndexRouteImport.update({
  id: '/recetas/',
  path: '/recetas/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasRecipeIdRoute = RecetasRecipeIdRouteImport.update({
  id: '/recetas/$recipeId',
  path: '/recetas/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasNuevaRoute = RecetasNuevaRouteImport.update({
  id: '/recetas/nueva',
  path: '/recetas/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasRecipeIdEditarRoute = RecetasRecipeIdEditarRouteImport.update({
  id: '/recetas/$recipeId_/editar',
  path: '/recetas/$recipeId/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bloqueados': typeof BloqueadosRoute
  '/comunidad': typeof ComunidadRoute
  '/crear-cuenta': typeof CrearCuentaRoute
  '/entrar': typeof EntrarRoute
  '/guardadas': typeof GuardadasRoute
  '/perfil': typeof PerfilRoute
  '/cocineros/$cookId': typeof CocinerosCookIdRoute
  '/recetas/$recipeId': typeof RecetasRecipeIdRoute
  '/recetas/nueva': typeof RecetasNuevaRoute
  '/recetas/': typeof RecetasIndexRoute
  '/recetas/$recipeId/editar': typeof RecetasRecipeIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bloqueados': typeof BloqueadosRoute
  '/comunidad': typeof ComunidadRoute
  '/crear-cuenta': typeof CrearCuentaRoute
  '/entrar': typeof EntrarRoute
  '/guardadas': typeof GuardadasRoute
  '/perfil': typeof PerfilRoute
  '/cocineros/$cookId': typeof CocinerosCookIdRoute
  '/recetas/$recipeId': typeof RecetasRecipeIdRoute
  '/recetas/nueva': typeof RecetasNuevaRoute
  '/recetas': typeof RecetasIndexRoute
  '/recetas/$recipeId/editar': typeof RecetasRecipeIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bloqueados': typeof BloqueadosRoute
  '/comunidad': typeof ComunidadRoute
  '/crear-cuenta': typeof CrearCuentaRoute
  '/entrar': typeof EntrarRoute
  '/guardadas': typeof GuardadasRoute
  '/perfil': typeof PerfilRoute
  '/cocineros/$cookId': typeof CocinerosCookIdRoute
  '/recetas/$recipeId': typeof RecetasRecipeIdRoute
  '/recetas/nueva': typeof RecetasNuevaRoute
  '/recetas/': typeof RecetasIndexRoute
  '/recetas/$recipeId_/editar': typeof RecetasRecipeIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bloqueados'
    | '/comunidad'
    | '/crear-cuenta'
    | '/entrar'
    | '/guardadas'
    | '/perfil'
    | '/cocineros/$cookId'
    | '/recetas/$recipeId'
    | '/recetas/nueva'
    | '/recetas/'
    | '/recetas/$recipeId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bloqueados'
    | '/comunidad'
    | '/crear-cuenta'
    | '/entrar'
    | '/guardadas'
    | '/perfil'
    | '/cocineros/$cookId'
    | '/recetas/$recipeId'
    | '/recetas/nueva'
    | '/recetas'
    | '/recetas/$recipeId/editar'
  id:
    | '__root__'
    | '/'
    | '/bloqueados'
    | '/comunidad'
    | '/crear-cuenta'
    | '/entrar'
    | '/guardadas'
    | '/perfil'
    | '/cocineros/$cookId'
    | '/recetas/$recipeId'
    | '/recetas/nueva'
    | '/recetas/'
    | '/recetas/$recipeId_/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BloqueadosRoute: typeof BloqueadosRoute
  ComunidadRoute: typeof ComunidadRoute
  CrearCuentaRoute: typeof CrearCuentaRoute
  EntrarRoute: typeof EntrarRoute
  GuardadasRoute: typeof GuardadasRoute
  PerfilRoute: typeof PerfilRoute
  CocinerosCookIdRoute: typeof CocinerosCookIdRoute
  RecetasRecipeIdRoute: typeof RecetasRecipeIdRoute
  RecetasNuevaRoute: typeof RecetasNuevaRoute
  RecetasIndexRoute: typeof RecetasIndexRoute
  RecetasRecipeIdEditarRoute: typeof RecetasRecipeIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueados': {
      id: '/bloqueados'
      path: '/bloqueados'
      fullPath: '/bloqueados'
      preLoaderRoute: typeof BloqueadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-cuenta': {
      id: '/crear-cuenta'
      path: '/crear-cuenta'
      fullPath: '/crear-cuenta'
      preLoaderRoute: typeof CrearCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardadas': {
      id: '/guardadas'
      path: '/guardadas'
      fullPath: '/guardadas'
      preLoaderRoute: typeof GuardadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocineros/$cookId': {
      id: '/cocineros/$cookId'
      path: '/cocineros/$cookId'
      fullPath: '/cocineros/$cookId'
      preLoaderRoute: typeof CocinerosCookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas/': {
      id: '/recetas/'
      path: '/recetas'
      fullPath: '/recetas/'
      preLoaderRoute: typeof RecetasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas/$recipeId': {
      id: '/recetas/$recipeId'
      path: '/recetas/$recipeId'
      fullPath: '/recetas/$recipeId'
      preLoaderRoute: typeof RecetasRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas/nueva': {
      id: '/recetas/nueva'
      path: '/recetas/nueva'
      fullPath: '/recetas/nueva'
      preLoaderRoute: typeof RecetasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas/$recipeId_/editar': {
      id: '/recetas/$recipeId_/editar'
      path: '/recetas/$recipeId/editar'
      fullPath: '/recetas/$recipeId/editar'
      preLoaderRoute: typeof RecetasRecipeIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BloqueadosRoute: BloqueadosRoute,
  ComunidadRoute: ComunidadRoute,
  CrearCuentaRoute: CrearCuentaRoute,
  EntrarRoute: EntrarRoute,
  GuardadasRoute: GuardadasRoute,
  PerfilRoute: PerfilRoute,
  CocinerosCookIdRoute: CocinerosCookIdRoute,
  RecetasRecipeIdRoute: RecetasRecipeIdRoute,
  RecetasNuevaRoute: RecetasNuevaRoute,
  RecetasIndexRoute: RecetasIndexRoute,
  RecetasRecipeIdEditarRoute: RecetasRecipeIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
